### ISSUE TITLE
Switch to mamba + miniforge = mambaforge to speed up CI?

### ISSUE THREAD

**Issue by jchodera** [MolSSI/cookiecutter-cms#139]
A great deal of developer time is spent waiting for CI to pass. 

Would it make sense to switch to [mambaforge](https://github.com/conda-forge/miniforge#mambaforge), a combination of [mamba](https://github.com/mamba-org/mamba) (a very fast version of `conda`) and [miniforge](https://github.com/conda-forge/miniforge) (a minimal conda-forge version of [miniconda](https://docs.conda.io/en/latest/miniconda.html))?

**Comment by jchodera** [comment]
Or perhaps we want [micromamba](https://github.com/mamba-org/mamba#micromamba)?

**Comment by jchodera** [comment]
Here's [an example that uses `mambaforge`](https://github.com/openkinome/kinoml/blob/master/.github/workflows/ci.yaml) for CI.

**Comment by Lnaden** [comment]
That's an idea I had not thought of. I'm all for making the CI faster, but I would want to do some more testing to get it implemented correctly. Right now the Cookiecutter uses roughly the same code for Conda and Conda-Forge dependency paths as the Conda-Forge path uses `main` as a fallback channel. If we were to use `mambaforge` the code would have to deviate some to get the channel order right, but I am all for testing this. 

I'll set up some local tests and do timing through docker containers. It wont be the greatest comparison, but it will be on the same platform at least and I can get of sense of what would need to change in the CI trees here.

**Comment by Lnaden** [comment]
I've done some testing with a few relatively simple environments comparing Mambaforge and Miniconda as close as I could. This doesn't account for network or CPU overhead really, but with a few samples hopefully that washes out.

In short:
* Mamba is faster
* If we want to drop this in, we need to change the educational side a bit as well for speed
* Need to discuss if we want to keep the `main` channel fallback
* I think I need a more practical "big" test case to really show speed up
* I've got this written up into a test script so I can setup and run again with minimal effort.
* I want to let this run overnight to increase sample size

The test case:

All of this is in seconds. Three tasks: Install from installer (pre-downloaded), solve dependencies for a simple test environment, solve dependencies for a larger test environment. Both test envs are dry runs so there should be no time for networking and the whole conda cache is cleaned between solves. All 3 tasks are carried out in 1 instance of a Docker container, 1 container for mamba and 1 for conda, container is deleted between runs. Sample size 10-11, rounded to nearest whole.

|  |Mean install | Mean small solve | Mean Big Solve |
| --- | --- | --- | --- |
| Mambaforge | 14 | 56 | 102 |
| Miniconda | 11 | 62 | 118 |
| Relative speed % | 78% | 110% | 115%|

Small Environment. Based on the cookiecutter defaults:
```yaml
name: small
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pytest
  - pytest-cov
  - codecov
```

Big Environment. Based on OpenMM Feedstock + some extra large packages
```yaml
name: big
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - fftw
  - swig
  - pthread-stubs
  - lxml
  - numpy
  - cython
  - ocl-icd
  - scipy
  - matplotliv
  - pytest
  - pytest-cov
  - codecov
 ```

**Comment by Lnaden** [comment]
I'd really like to get a more complex solve to test this against to highlight just how much of a speedup mamba can be. I could just grab one of my more complex local envs, but would prefer practical envs if people have suggestions.

**Comment by jchodera** [comment]
@jaimergp set up [this example](https://github.com/openkinome/kinoml/blob/master/.github/workflows/ci.yaml) for us, so either he could chime in with what he found empirically or we could try timing mambaforge vs miniconda. It's about as complex as it gets.

**Comment by jaimergp** [comment]
Fastest solution is to [provision with Micromamba](https://github.com/mamba-org/provision-with-micromamba#inputs), in my experience.

For complex solves, add some compilers in the mix and the sysroot for 2.17.

**Comment by mikemhenry** [comment]
I haven't tested provisioning with micromamba yet, but some data on just the difference in using mamba instead of conda in our CI is here: https://github.com/choderalab/perses/pull/850#issuecomment-906798324

| conda | mamba (this PR) |
| ------------- | ------------- |
| 8m 39s | 5m 11s |
| 8m 50s | 5m 13s   |
| 8m 32s | 4m 37s   |
| 9m 30s | 4m 56s   |
| 7m 12s | 5m 30s   |
| 7m 17s | 5m 18s   |

**Comment by radifar** [comment]
I've already switched to micromamba, my project is small with just 3 dependencies (Openbabel, Numpy, and Bitstring), the CI uses Linux, Windows, MacOS and Python 3.6, 3.7, 3.8. And I've got the time range of 4-5 minutes using miniconda, and 3-4 minutes using `provision with micromamba` GHA.

The caveat is I haven't figured out how to supply the Python version value to this GHA, so I use different yaml environment file for each Python version.

```yaml
    - uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: devtools/conda-envs/test_env-${{ matrix.python-version }}.yaml
        environment-name: python-${{ matrix.python-version }}-env
```

@jaimergp any thought on this?
