### ISSUE TITLE
Move away from CI with conda-build

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/cookiecutter-cms#50]
This is something that we discuss a bit internally but could use some additional discussion. In general, conda-build is fairly complicated and errors can be quite opaque. With the rise of host, run, requires, import, build, etc the `meta.yaml` files are becoming increasingly complex and not particularly sustainable for the average user even though they make good sense for CD integrity.

In addition, there seems to be a continuous movement towards deploying with `conda-forge` rather than custom channels. This has the benefit that `meta.yaml`'s can be templated off the continuously updated c-f templates, a large community of reviewers can examine the `meta.yaml`'s before merging, and c-f's bots can update out of date `meta.yaml`'s automatically. In addition, c-f's build, deployment, and auto update on release technology will provide a far easier experience than someone trying to deploy on their own. 

I would propose using `conda install` for travis/appveyor instead where we can either have users list dependencies in the `travis.yaml` or use [environment](https://github.com/MolSSI/QCFractal/blob/master/devtools/conda-envs/openff.yaml) files using a script similar to [this](https://github.com/MolSSI/QCFractal/blob/master/devtools/scripts/conda_env.py). This has the benefit that builds are much quicker often (3-4x) due to less redundancy in the build cycles and the overall cognitive overhead is much lower as cookiecutter users can use canonical conda commands.

Using straight `conda install` will increase the dependency duplication slightly with `setup.py`, `appveyor.yaml`, and `travis.yaml`. The environments have the benefit of keeping duplication the same and providing developers and users a clean and reusable development/execution environment with the downside the complexity is slightly increased I would think.

Thoughts?

**Comment by jchodera** [comment]
I'd love to see what an example of this might look like!

**Comment by dgasmith** [comment]
## Conda-build (current)
```yaml
    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
  - conda activate test

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local repo_name
```

`meta.yaml`
```yaml
package:
  name: qcfractal
  version: "0.0.0" # Must manually bump

source:
  path: ../..

build:
  number: 0 # Must manually bump
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy 
    - scipy
    - ...

test:
  requires:
    - python
    - pytest
  commands:
    - py.test --pyargs package
  imports:
    - package

about:
  home: https://github.com/MolSSI/QCFractal
  license: BSD-3-Clause License
```

## Conda install explicit list
```yaml
  - conda install python=$PYTHON_VER numpy scipy ...
  - python setup.py develop --no-deps
```

## Conda environment
```yaml
  - python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/base.yaml
  - python setup.py develop --no-deps
```

`base.yaml`
```yaml
name: test
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - ...
```

New developers can also just run `python devtools/scripts/conda_env.py -n=test -p=3.6 devtools/conda-envs/base.yaml` to get a full development environment.
