### ISSUE TITLE
Revisiting conda caching

### ISSUE THREAD

**Issue by dgasmith** [MolSSI/cookiecutter-cms#71]
@robertodr hit on a simple, yet effective way to cache conda envs. I normally push back against caching due to the chances of issues which can be substantial with confusing errors, but this way we use all of conda's native caching to handle this which should reduce the chance of problems. Setting the timeout to something reasonable short as shown below will help during peak access on a repository. Something that we should try out to make sure it is robust before deploying here.

```
before_cache:
  - conda deactivate
  - conda remove --name test --all
cache:
  timeout: 1000
  directories:
    - $HOME/miniconda
```
